try:
  n = int(input())
except Exception as e:
  print('Exception occured',e,type(e)._name_)
